services:
  - type: web
    name: code-review-assistant
    env: java
    plan: free
    region: oregon
    branch: main
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 10000
